<a href="https://colab.research.google.com/github/narcisoleedev/data_analysis_learning/blob/main/Numpy_and_Pandas_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy Training
From: Guilherme N. Lee


## Why Numpy
  Numpy is a python library that helps you optimize numbers memory storing using C tricks, which helps a lot on processing of Big Data. For example, you can optimize a variable to receive an int of size 8 (bytes) instead of 20 (bytes) as usually Python does, due to it's being high level programming language. For more information, see: Binary Arythmetic.

In [ ]:
import numpy as np
import sys

For more information, see: Free Code Camp's Numpy Notebook.

In [ ]:
#An array
ar = np.array([1, 2, 3, 4])
ar[0], ar[1]

(1, 2)

In [ ]:
bar = np.array([[1,2,3,4],[4,5,6,7]])
bar.size

8

In [ ]:
bar.ndim

2

In [ ]:
bar.shape

(2, 4)

In [ ]:
bar[0][0]

1

In [ ]:
bar[:1]

array([[1, 2, 3, 4]])

In [ ]:
#Vertical is dimension 0, and horizontal, 1.
bar.mean(axis=0)


array([2.5, 3.5, 4.5, 5.5])

In [ ]:
bar.mean()

4.0

## Broadcasting and Vectorized operations


In [ ]:
vec = np.arange(5)
vec + 20

array([20, 21, 22, 23, 24])

## Boolean operations (Masks)

In [ ]:
bol = np.arange(10)
bol[bol%2==0]

array([0, 2, 4, 6, 8])

In [ ]:
bol%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [ ]:
ranmatrice = np.random.randint(100,size=(3,3))
print(ranmatrice)

[[57 52 74]
 [ 5 43 92]
 [ 4 45 48]]


Linear Algebra and other functions can been seen in FCC's notebook.

## Memory

In [ ]:
sys.getsizeof(1)


28

In [ ]:
sys.getsizeof(100*100)

28

In [ ]:
np.dtype(np.int8).itemsize

1

In [ ]:
np.dtype(int).itemsize

8

In [ ]:
#Performance comparation
listnonumpy = list(range(1000))
%time sum([x**2 for x in listnonumpy])

CPU times: user 494 µs, sys: 0 ns, total: 494 µs
Wall time: 502 µs


332833500

In [ ]:
listnumpy = np.arange(1000)
%time np.sum(listnumpy**2)

CPU times: user 97 µs, sys: 12 µs, total: 109 µs
Wall time: 646 µs


332833500

# Pandas
  Pandas are a library in Python that's helps a lot during data analysis and manipulation.
  

In [ ]:
import pandas as pd


## Series
Series are similar to Dictionaries in python as it'll be shown below, but its orderer like an array.

In [ ]:
ser = pd.Series([1.75, 1.74, 1.70, 1.71])
ser

0    1.75
1    1.74
2    1.70
3    1.71
dtype: float64

In [ ]:
ser.name = 'My friends and mine height:'


In [ ]:
ser.index =(['Me', 'Vini', 'Diogo', 'Fernanda'])
ser

Me          1.75
Vini        1.74
Diogo       1.70
Fernanda    1.71
Name: My friends and mine height:, dtype: float64

In [ ]:
ser.values

array([1.75, 1.74, 1.7 , 1.71])

In [ ]:
ser['Me']

1.75

### Indexing

In [ ]:
#Locate by sequential position
ser.iloc[-1]

1.71

In [ ]:
ser.iloc[[0, 1]]

Me      1.75
Vini    1.74
Name: My friends and mine height:, dtype: float64

In [ ]:
ser['Me': 'Diogo']

Me       1.75
Vini     1.74
Diogo    1.70
Name: My friends and mine height:, dtype: float64

### Conditionals

In [ ]:
ser.size > 2

True

In [ ]:
ser > 1.72

Me           True
Vini         True
Diogo       False
Fernanda    False
Name: My friends and mine height:, dtype: bool

In [ ]:
ser[ser>ser.mean()]

Me      1.75
Vini    1.74
Name: My friends and mine height:, dtype: float64

## Dataframes
Its like an Excel table and therefore, an matrice.




In [ ]:
# 'tomfc' means table of my friends' characteristcs
tomfc = pd.DataFrame({
    'When I first meet':  [0, 0, 15, 15, 15, 15],
    'Gender': ['M', 'M', 'M', 'M', 'M', 'F'],
    'Favorite Anime': ['Monogatari Series', 'One Piece', 'Kengan Ashura', 'TTGL', 'One Piece', 'Sailor Moon']
})

In [ ]:
tomfc

When I first meet Gender     Favorite Anime
0                  0      M  Monogatari Series
1                  0      M          One Piece
2                 15      M      Kengan Ashura
3                 15      M               TTGL
4                 15      M          One Piece
5                 15      F        Sailor Moon

In [ ]:
tomfc.index = ['Me', 'Pedro', 'Christian', 'Vini', 'Diogo', 'Fernanda']

In [ ]:
tomfc

When I first meet Gender     Favorite Anime
Me                         0      M  Monogatari Series
Pedro                      0      M          One Piece
Christian                 15      M      Kengan Ashura
Vini                      15      M               TTGL
Diogo                     15      M          One Piece
Fernanda                  15      F        Sailor Moon

In [ ]:
tomfc.shape

(6, 3)

In [ ]:
tomfc.info

<bound method DataFrame.info of            When I first meet Gender     Favorite Anime
Me                         0      M  Monogatari Series
Pedro                      0      M          One Piece
Christian                 15      M      Kengan Ashura
Vini                      15      M               TTGL
Diogo                     15      M          One Piece
Fernanda                  15      F        Sailor Moon>

In [ ]:
tomfc.describe()

When I first meet
count           6.000000
mean           10.000000
std             7.745967
min             0.000000
25%             3.750000
50%            15.000000
75%            15.000000
max            15.000000

In [ ]:
tomfc.dtypes

When I first meet     int64
Gender               object
Favorite Anime       object
dtype: object

###Indexing, Selecting, Slicing

In [ ]:
tomfc.loc['Me']

When I first meet                    0
Gender                               M
Favorite Anime       Monogatari Series
Name: Me, dtype: object

In [ ]:
tomfc['Favorite Anime']

Me           Monogatari Series
Pedro                One Piece
Christian        Kengan Ashura
Vini                      TTGL
Diogo                One Piece
Fernanda           Sailor Moon
Name: Favorite Anime, dtype: object

In [ ]:
tomfc.loc['Me': 'Christian', 'Favorite Anime']

Me           Monogatari Series
Pedro                One Piece
Christian        Kengan Ashura
Name: Favorite Anime, dtype: object

### Boolean and dropping


In [ ]:
tomfc['When I first meet'] > 14

Me           False
Pedro        False
Christian     True
Vini          True
Diogo         True
Fernanda      True
Name: When I first meet, dtype: bool

In [ ]:
tomfc.drop('Me')


When I first meet Gender Favorite Anime
Pedro                      0      M      One Piece
Christian                 15      M  Kengan Ashura
Vini                      15      M           TTGL
Diogo                     15      M      One Piece
Fernanda                  15      F    Sailor Moon

In [ ]:
tomfc.drop(columns=['Gender', 'When I first meet'])

Favorite Anime
Me         Monogatari Series
Pedro              One Piece
Christian      Kengan Ashura
Vini                    TTGL
Diogo              One Piece
Fernanda         Sailor Moon

###Operations with series


In [ ]:
minuswifm = pd.Series([-10], index=["When I first meet"])

In [ ]:
tomfc + minuswifm

Favorite Anime Gender  When I first meet
Me                   NaN    NaN              -10.0
Pedro                NaN    NaN              -10.0
Christian            NaN    NaN                5.0
Vini                 NaN    NaN                5.0
Diogo                NaN    NaN                5.0
Fernanda             NaN    NaN                5.0

In [ ]:
tomfc['When I first meet'] + minuswifm

Christian           NaN
Diogo               NaN
Fernanda            NaN
Me                  NaN
Pedro               NaN
Vini                NaN
When I first meet   NaN
dtype: float64

In [ ]:
graduation = pd.Series(['IS', 'EP', 'CC', 'EM', 'EE', 'BT'], index=['Me', 'Pedro', 'Christian', 'Vini', 'Diogo', 'Fernanda'], name='Graduation')
tomfc['Graduation'] = graduation
tomfc

When I first meet Gender     Favorite Anime Graduation
Me                         0      M  Monogatari Series         IS
Pedro                      0      M          One Piece         EP
Christian                 15      M      Kengan Ashura         CC
Vini                      15      M               TTGL         EM
Diogo                     15      M          One Piece         EE
Fernanda                  15      F        Sailor Moon         BT

In [ ]:
tomfc['Gender'] = 'H'
tomfc

When I first meet Gender     Favorite Anime Graduation
Me                         0      H  Monogatari Series         IS
Pedro                      0      H          One Piece         EP
Christian                 15      H      Kengan Ashura         CC
Vini                      15      H               TTGL         EM
Diogo                     15      H          One Piece         EE
Fernanda                  15      H        Sailor Moon         BT

In [ ]:
tren = tomfc.rename(
    columns={
        'When I first meet': 'WIFM',
        'Gender': 'Sex',
        'Graduation': 'Grad'
    }, index={ 
        'Me':'Guilherme'
    }
)

In [ ]:
tren.sum()['WIFM']

60